apiVersion: v1
kind: PersistentVolume
metadata:
  name: fishlo-storage-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/symul/storage
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fishlo-storage-pvc
spec:
  volumeName: fishlo-storage-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fishlo
spec:
  replicas: 1

  selector:
    matchLabels:
      app: fishlo

  template:
    metadata:
      labels:
        app: fishlo

    spec:
      containers:
        - name: fishlo
          image: saimonpranta/fishlo:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          env:
            - name: NODE_ENV
              value: "production"

            - name: PORT
              value: "3000"

            - name: HOSTNAME
              value: "0.0.0.0"

            - name: STORAGE_DIR
              value: "../storage/fishlo"

            - name: JWT_SECRET
              value: "S3u8AlsfA"

            - name: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
              value: "faketada"

            - name: STRIPE_SECRET_KEY
              value: "faketada"

            - name: DB_HOST
              value: "mysql-service"

            - name: DB_USER
              value: "prisma_user"

            - name: DB_PASSWORD
              value: "Prisma12345"

            - name: DB_NAME
              value: "fishlo"

            - name: DB_PORT
              value: "3306"

          volumeMounts:
            - name: fishlo-storage
              mountPath: /app/storage

      volumes:
        - name: fishlo-storage
          persistentVolumeClaim:
            claimName: fishlo-storage-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: fishlo-service
spec:
  selector:
    app: fishlo

  ports:
    - name: http
      port: 3000
      targetPort: 3000

  type: ClusterIP